name: Half-year calendar
on:
 schedule:
   - cron: "0 */24 * * *" 
 workflow_dispatch:
 push:
   branches:
     - master
jobs:
 generate:
   runs-on: ubuntu-latest
   timeout-minutes: 10
   steps:
     - name: generate metrics.plugin.isocalendar.svg
       uses: lowlighter/metrics@latest
       with:
         github_user_name: ${{ github.repository_owner }}
         outputs: |
           dist/metrics.plugin.isocalendar.svg
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     - name: push metrics.plugin.isocalendar.svg to the output branch
       uses: lowlighter/metrics@latest
       with:
         target_branch: output
         build_dir: dist
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
