name: Half-year calendar
uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.isocalendar.svg
  token: ${{ secrets.METRICS_TOKEN }}
  base: ""
  plugin_isocalendar: yes

on:
  schedule:

    - cron: "0 0 * * *"
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate metrics.plugin.isocalendar.svg
        uses: lowlighter/metrics@latest
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/metrics.plugin.isocalendar.svg
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
      - name: Push metrics.plugin.isocalendar.svg to the output branch
        uses: lowlighter/metrics@latest
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
